name: Generate Work Tracker Metrics

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Generate Work Tracker
        env:
          STATS_URL: ${{ secrets.STATS_URL }}
          API_SECRET_TOKEN: ${{ secrets.API_SECRET_TOKEN }}
        run: node index.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "docs: update work tracker statistics [skip ci]" || echo "No changes to commit"
          git push